/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FarmsIndexImport } from './routes/farms/index'
import { Route as FarmsContractAddressImport } from './routes/farms/$contractAddress'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FarmsIndexRoute = FarmsIndexImport.update({
  path: '/farms/',
  getParentRoute: () => rootRoute,
} as any)

const FarmsContractAddressRoute = FarmsContractAddressImport.update({
  path: '/farms/$contractAddress',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/farms/$contractAddress': {
      preLoaderRoute: typeof FarmsContractAddressImport
      parentRoute: typeof rootRoute
    }
    '/farms/': {
      preLoaderRoute: typeof FarmsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  FarmsContractAddressRoute,
  FarmsIndexRoute,
])

/* prettier-ignore-end */
